In [1]:
#
import numpy as np
import pandas as pd
import f3dasm
from f3dasm import ExperimentData

In [2]:
# read the results
original_exp = ExperimentData.from_file(
    filename='experiments/exp_20d_problem',)
# # new results on diff
# new_exp = ExperimentData.from_file(
#     filename='new_experiments/exp_50d_problem')

In [3]:
original_exp

In [4]:
# merge the input_data and output_data into one pd.DataFrame
original_df = pd.concat([original_exp.input_data.data, original_exp.output_data.data],
                        axis=1)

In [5]:
# have the mean of the results according to the method
original_df_mean = original_df.groupby('method').mean()

# standard deviation
original_df_std = original_df.groupby('method').std()

In [6]:
original_df_mean

,seed,nmae,nrmse,r2,log_likelihood,lf_nmae,lf_nrmse,lf_re,beta_0,beta_1
method,,,,,,,,,,
bnn,5.5,1.240681,0.198670,0.597997,-18.826017,0.000000,0.000000,0.000000,0.000000,0.000000
dnn_bnn,5.5,0.933497,0.113771,0.867892,-9.124022,0.489480,0.088384,0.927925,0.000000,0.000000
dnn_lr_bnn,5.5,0.632505,0.109176,0.878406,-9.883009,0.485448,0.088732,0.927337,49.421287,1.261595

In [7]:
original_df_std

,seed,nmae,nrmse,r2,log_likelihood,lf_nmae,lf_nrmse,lf_re,beta_0,beta_1
method,,,,,,,,,,
bnn,3.02765,0.164514,0.007130,0.029124,1.433135,0.000000,0.000000,0.000000,0.000000,0.000000
dnn_bnn,3.02765,0.181909,0.006814,0.015618,0.696312,0.059662,0.005361,0.008415,0.000000,0.000000
dnn_lr_bnn,3.02765,0.116352,0.006040,0.012964,0.596776,0.058594,0.005606,0.008909,9.579339,0.004672